/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.alura.jean_dlcr.currencyconverter.view.main.about;

import com.alura.jean_dlcr.currencyconverter.util.Helper;
import com.alura.jean_dlcr.currencyconverter.util.RoundButton;
import java.awt.Desktop;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JScrollPane;
import javax.swing.event.HyperlinkEvent;
import com.alura.jean_dlcr.currencyconverter.util.IHasScrollPane;

/**
 *
 * @author Jean
 */
public class JPAbout extends javax.swing.JPanel implements IHasScrollPane{

    /**
     * Creates new form JPRecord
     */
    
    private static Icon iconGithub;
    
    public JPAbout() {
        setIconGithub();
        initComponents();
        Helper.addHiperLink(txtPnl);
    }
    
    @Override
    public JScrollPane getScrollPane() {
        return scrollPane;
    }
    
    private void setIconGithub(){
        iconGithub = new ImageIcon(new ImageIcon(getClass().getResource("/assets/icons/github.png"))
                                .getImage()
                                .getScaledInstance(18, 18, Image.SCALE_SMOOTH));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane = new javax.swing.JScrollPane();
        txtPnl = new javax.swing.JTextPane();
        btnGithub = new RoundButton("", 15, iconGithub,15);

        scrollPane.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        scrollPane.setPreferredSize(new java.awt.Dimension(370, 195));

        txtPnl.setEditable(false);
        txtPnl.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        txtPnl.setContentType("text/html"); // NOI18N
        txtPnl.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtPnl.setOpaque(false);
        scrollPane.setViewportView(txtPnl);

        btnGithub.setBackground(new java.awt.Color(32, 32, 32));
        btnGithub.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnGithub.setForeground(new java.awt.Color(255, 255, 255));
        btnGithub.setText("jButton1");
        btnGithub.setBorder(null);
        btnGithub.setBorderPainted(false);
        btnGithub.setContentAreaFilled(false);
        btnGithub.setFocusPainted(false);
        btnGithub.setFocusable(false);
        btnGithub.setMargin(new java.awt.Insets(5, 5, 5, 5));
        btnGithub.setMaximumSize(new java.awt.Dimension(100, 100));
        btnGithub.setMinimumSize(new java.awt.Dimension(0, 0));
        btnGithub.setPreferredSize(new java.awt.Dimension(160, 35));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(btnGithub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(120, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(15, Short.MAX_VALUE)
                    .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(15, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(217, Short.MAX_VALUE)
                .addComponent(btnGithub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(12, Short.MAX_VALUE)
                    .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(63, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnGithub;
    public javax.swing.JScrollPane scrollPane;
    public javax.swing.JTextPane txtPnl;
    // End of variables declaration//GEN-END:variables
}
