/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.alura.jean_dlcr.currencyconverter.view.main.converter;

import com.alura.jean_dlcr.currencyconverter.model.currency.CurrencyItem;
import com.alura.jean_dlcr.currencyconverter.util.RoundButton;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.geom.AffineTransform;
import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;
import javax.swing.JButton;

/**
 *
 * @author Jean
 */
public class JPConverter extends javax.swing.JPanel {

    /**
     * Creates new form JPConverter
     */
    public JPConverter() {
        initComponents();
        this.btnChangeOrder.setIcon(new ImageIcon(new ImageIcon(getClass().getResource("/assets/icons/bidirectional.png")).getImage().getScaledInstance(28, 28, Image.SCALE_SMOOTH)));
    }
    
    public void rotateButtonIcon(JButton button, int angle) {
        ImageIcon icon = (ImageIcon) button.getIcon();
        if (icon != null) {
            Image image = icon.getImage();
            BufferedImage bufferedImage = new BufferedImage(
                    image.getWidth(null), image.getHeight(null), BufferedImage.TYPE_INT_ARGB);

            Graphics2D g2d = bufferedImage.createGraphics();

            // Rotar la imagen 180 grados alrededor de su centro
            AffineTransform transform = new AffineTransform();
            transform.rotate(Math.toRadians(angle), image.getWidth(null) / 2.0, image.getHeight(null) / 2.0);
            g2d.setTransform(transform);

            // Dibujar la imagen rotada
            g2d.drawImage(image, 0, 0, null);
            g2d.dispose();

            // Configurar el ícono rotado en el botón
            button.setIcon(new ImageIcon(bufferedImage));
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        cboCurrency1 = new javax.swing.JComboBox<>();
        txtInputFrom = new javax.swing.JTextField();
        cboCurrency2 = new javax.swing.JComboBox<>();
        btnChangeOrder = new javax.swing.JButton();
        txtResultConverted = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        btnConverter = new RoundButton("", 15);

        setLayout(new java.awt.GridBagLayout());

        java.awt.GridBagLayout jPanel1Layout = new java.awt.GridBagLayout();
        jPanel1Layout.columnWidths = new int[] {0};
        jPanel1Layout.rowHeights = new int[] {0};
        jPanel1Layout.columnWeights = new double[] {1.0};
        jPanel1Layout.rowWeights = new double[] {1.0};
        jPanel1.setLayout(jPanel1Layout);

        jPanel4.setPreferredSize(new java.awt.Dimension(223, 145));

        cboCurrency1.setMaximumSize(new java.awt.Dimension(200, 200));
        cboCurrency1.setMinimumSize(new java.awt.Dimension(0, 0));
        cboCurrency1.setPreferredSize(new java.awt.Dimension(85, 35));

        txtInputFrom.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtInputFrom.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtInputFrom.setMaximumSize(new java.awt.Dimension(200, 200));
        txtInputFrom.setMinimumSize(new java.awt.Dimension(0, 0));
        txtInputFrom.setPreferredSize(new java.awt.Dimension(120, 35));

        cboCurrency2.setMaximumSize(new java.awt.Dimension(200, 200));
        cboCurrency2.setMinimumSize(new java.awt.Dimension(0, 0));
        cboCurrency2.setPreferredSize(new java.awt.Dimension(85, 35));

        btnChangeOrder.setMaximumSize(new java.awt.Dimension(200, 200));
        btnChangeOrder.setMinimumSize(new java.awt.Dimension(0, 0));
        btnChangeOrder.setPreferredSize(new java.awt.Dimension(100, 35));

        txtResultConverted.setEditable(false);
        txtResultConverted.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtResultConverted.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtResultConverted.setMaximumSize(new java.awt.Dimension(200, 200));
        txtResultConverted.setMinimumSize(new java.awt.Dimension(0, 0));
        txtResultConverted.setPreferredSize(new java.awt.Dimension(120, 35));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txtResultConverted, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboCurrency2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnChangeOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(cboCurrency1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(txtInputFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(btnChangeOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtResultConverted, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboCurrency2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cboCurrency1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtInputFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(104, Short.MAX_VALUE)))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel1.add(jPanel4, gridBagConstraints);

        jPanel5.setPreferredSize(new java.awt.Dimension(223, 60));
        jPanel5.setLayout(new java.awt.GridBagLayout());

        btnConverter.setBackground(new java.awt.Color(42, 122, 228));
        btnConverter.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnConverter.setForeground(new java.awt.Color(255, 255, 255));
        btnConverter.setText("jButton1");
        btnConverter.setBorder(null);
        btnConverter.setBorderPainted(false);
        btnConverter.setContentAreaFilled(false);
        btnConverter.setFocusPainted(false);
        btnConverter.setFocusable(false);
        btnConverter.setMargin(new java.awt.Insets(5, 5, 5, 5));
        btnConverter.setMaximumSize(new java.awt.Dimension(100, 100));
        btnConverter.setMinimumSize(new java.awt.Dimension(0, 0));
        btnConverter.setPreferredSize(new java.awt.Dimension(88, 35));
        jPanel5.add(btnConverter, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        jPanel1.add(jPanel5, gridBagConstraints);

        add(jPanel1, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnChangeOrder;
    public javax.swing.JButton btnConverter;
    public javax.swing.JComboBox<CurrencyItem> cboCurrency1;
    public javax.swing.JComboBox<CurrencyItem> cboCurrency2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    public javax.swing.JTextField txtInputFrom;
    public javax.swing.JTextField txtResultConverted;
    // End of variables declaration//GEN-END:variables
}
