## Downlaod flag from.

flagURL: "https://flagcdn.com/w160/es.png"

CONFIG_API:
    dialogTitle: "Ingrese el API_KEY"
    configInstructions: '<p>Si no tiene un api key, regístrese en <a href="%s">%s</a> es gratis.Sugiero revisar la <a href="%s">Documentación</a></p> '
    btnSave: "Guardar"
    btnCancel: "Cancelar"
    wrongAPIkey: "API KEY inválido. Intente nuevamente."

WELCOME:
  welcomeTo: "Bienvenido a"
  description: | 
    Tu herramienta confiable para cotizar el intercambio de divisas. Ingresa la cantidad, selecciona el par de monedas que deseas convertir, y descubre el valor en tiempo real.

    Antes de empezar, selecciona tu idioma.
  btnStart: "Empezar"

MENUBUTTONS:  
    btnConverter: "Convertir"
    btnRecord: "Historial"
    btnHelp: "Ayuda"
    btnAbout: "Acerca de"
  
CONVERTER:
    btnConverter: "Convertir"
    errorInvalidInputTitle: "Número Inválido"
    errorInvalidInput: "Por favor ingrese un número válido para hacer la conversión."

RECORD:
    title: "Historial"
    tblHeader: "Hora, De, Monto, Al, Total"
    errorTblHeader: "Error en archivo de lenguaje.\nSe necesitan %s columnas para la tabla del historial."


HELP:
    title: "Ayuda"
    step1: "Seleccione una moneda de origen."
    step2: "Ingrese la cantidad a cotizar."
    step3: "Seleccione una moneda de destino."
    step4: "De clic en %s para procesar el cambio."
    note1: "Intercambia las monedas de origen y destino."
    
    
    