/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.alura.jean_dlcr.currencyconverter.view.welcome;

import com.alura.jean_dlcr.currencyconverter.model.lang.LanguageItem;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Jean
 */
public class JPCustomFlagItemCbo extends javax.swing.JPanel {

    /**
     * Creates new form customList
     */
    public JPCustomFlagItemCbo() {
        initComponents();
    }

    public void setData(String flagPath, String label) {
        float height = (float) imgFlag.getPreferredSize().getHeight();
        if (height <= 0) {
            height = 15f;
        }
        ImageIcon icon = new ImageIcon(new ImageIcon(flagPath).getImage().getScaledInstance((int) (4 * (height / 3)), (int) height, Image.SCALE_SMOOTH));
        imgFlag.setIcon(icon);
        langLabel.setText(label);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imgFlag = new javax.swing.JLabel();
        langLabel = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        setMaximumSize(new java.awt.Dimension(0, 0));
        setMinimumSize(new java.awt.Dimension(0, 0));
        setPreferredSize(new java.awt.Dimension(0, 20));
        setLayout(new java.awt.BorderLayout());

        imgFlag.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgFlag.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        imgFlag.setMaximumSize(new java.awt.Dimension(100, 100));
        imgFlag.setPreferredSize(new java.awt.Dimension(30, 0));
        add(imgFlag, java.awt.BorderLayout.WEST);

        langLabel.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        langLabel.setText("HOLA MUNDO");
        langLabel.setMaximumSize(new java.awt.Dimension(100, 100));
        langLabel.setMinimumSize(new java.awt.Dimension(0, 0));
        langLabel.setPreferredSize(new java.awt.Dimension(80, 14));
        add(langLabel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imgFlag;
    public javax.swing.JLabel langLabel;
    // End of variables declaration//GEN-END:variables
}
